export const SET_WEATHER_IN_CURRENT_GEO = "SET_WEATHER_IN_CURRENT_GEO"
export const SET_WEATHER_IN_CITY = "SET_WEATHER_IN_CITY"
export const SET_GEOCODE_IN_CURRENT_GEO = "SET_GEOCODE_IN_CURRENT_GEO"
export const DELETE_CITY = "DELETE_CITY"